const TEAM_MAP: Record<string, string> = {
  'adelaide': 'Adelaide',
  'adelaide crows': 'Adelaide',
  'crows': 'Adelaide',
  'brisbane': 'Brisbane',
  'brisbane lions': 'Brisbane',
  'lions': 'Brisbane',
  'carlton': 'Carlton',
  'carlton blues': 'Carlton',
  'blues': 'Carlton',
  'collingwood': 'Collingwood',
  'collingwood magpies': 'Collingwood',
  'magpies': 'Collingwood',
  'pies': 'Collingwood',
  'essendon': 'Essendon',
  'essendon bombers': 'Essendon',
  'bombers': 'Essendon',
  'fremantle': 'Fremantle',
  'fremantle dockers': 'Fremantle',
  'dockers': 'Fremantle',
  'geelong': 'Geelong',
  'geelong cats': 'Geelong',
  'cats': 'Geelong',
  'gold coast': 'Gold Coast',
  'gold coast suns': 'Gold Coast',
  'suns': 'Gold Coast',
  'gold-coast': 'Gold Coast',
  'gws': 'GWS',
  'gws giants': 'GWS',
  'greater western sydney': 'GWS',
  'greater western sydney giants': 'GWS',
  'giants': 'GWS',
  'hawthorn': 'Hawthorn',
  'hawthorn hawks': 'Hawthorn',
  'hawks': 'Hawthorn',
  'melbourne': 'Melbourne',
  'melbourne demons': 'Melbourne',
  'demons': 'Melbourne',
  'dees': 'Melbourne',
  'north melbourne': 'North Melbourne',
  'north melbourne kangaroos': 'North Melbourne',
  'kangaroos': 'North Melbourne',
  'roos': 'North Melbourne',
  'north-melbourne': 'North Melbourne',
  'port adelaide': 'Port Adelaide',
  'port adelaide power': 'Port Adelaide',
  'power': 'Port Adelaide',
  'port-adelaide': 'Port Adelaide',
  'richmond': 'Richmond',
  'richmond tigers': 'Richmond',
  'tigers': 'Richmond',
  'st kilda': 'St Kilda',
  'st kilda saints': 'St Kilda',
  'saints': 'St Kilda',
  'st-kilda': 'St Kilda',
  'sydney': 'Sydney',
  'sydney swans': 'Sydney',
  'swans': 'Sydney',
  'west coast': 'West Coast',
  'west coast eagles': 'West Coast',
  'eagles': 'West Coast',
  'west-coast': 'West Coast',
  'western bulldogs': 'Western Bulldogs',
  'western-bulldogs': 'Western Bulldogs',
  'bulldogs': 'Western Bulldogs',
  'dogs': 'Western Bulldogs',
};

export const CANONICAL_TEAMS = [
  'Adelaide',
  'Brisbane',
  'Carlton',
  'Collingwood',
  'Essendon',
  'Fremantle',
  'Geelong',
  'Gold Coast',
  'GWS',
  'Hawthorn',
  'Melbourne',
  'North Melbourne',
  'Port Adelaide',
  'Richmond',
  'St Kilda',
  'Sydney',
  'West Coast',
  'Western Bulldogs',
];

export function normalizeTeam(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const key = raw.trim().toLowerCase();
  return TEAM_MAP[key] ?? raw.trim();
}
